=== streamentry/LitMundi/corpus/schemas/alignment.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "LitMundi Many-to-Many Alignment",
  "type": "object",
  "required": [
    "schema_version",
    "work_id",
    "edition_id",
    "source_edition_id",
    "links"
  ],
  "properties": {
    "schema_version": {
      "const": 1
    },
    "work_id": {
      "type": "string"
    },
    "edition_id": {
      "type": "string"
    },
    "source_edition_id": {
      "type": "string"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "source",
          "target"
        ],
        "properties": {
          "source": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "type": "string"
            }
          },
          "target": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "type": "string"
            }
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== streamentry/LitMundi/corpus/alignments/saki-the-open-window/saki-open-window-vi-ai-2026.json
{
  "schema_version": 1,
  "work_id": "saki-the-open-window",
  "edition_id": "saki-open-window-vi-ai-2026",
  "source_edition_id": "saki-open-window-en-john-lane-1914",
  "links": [
    {
      "source": [
        "saki-the-open-window:1.1"
      ],
      "target": [
        "saki-the-open-window:1.1"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.2"
      ],
      "target": [
        "saki-the-open-window:1.2"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.3"
      ],
      "target": [
        "saki-the-open-window:1.3"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.4"
      ],
      "target": [
        "saki-the-open-window:1.4"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.5"
      ],
      "target": [
        "saki-the-open-window:1.5"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.6"
      ],
      "target": [
        "saki-the-open-window:1.6"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.7"
      ],
      "target": [
        "saki-the-open-window:1.7"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.8"
      ],
      "target": [
        "saki-the-open-window:1.8"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.9"
      ],
      "target": [
        "saki-the-open-window:1.9"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.10"
      ],
      "target": [
        "saki-the-open-window:1.10"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.11"
      ],
      "target": [
        "saki-the-open-window:1.11"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.12"
      ],
      "target": [
        "saki-the-open-window:1.12"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.13"
      ],
      "target": [
        "saki-the-open-window:1.13"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.14"
      ],
      "target": [
        "saki-the-open-window:1.14"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.15"
      ],
      "target": [
        "saki-the-open-window:1.15"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.16"
      ],
      "target": [
        "saki-the-open-window:1.16"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.17"
      ],
      "target": [
        "saki-the-open-window:1.17"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.18"
      ],
      "target": [
        "saki-the-open-window:1.18"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.19"
      ],
      "target": [
        "saki-the-open-window:1.19"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.20"
      ],
      "target": [
        "saki-the-open-window:1.20"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.21"
      ],
      "target": [
        "saki-the-open-window:1.21"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.22"
      ],
      "target": [
        "saki-the-open-window:1.22"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.23"
      ],
      "target": [
        "saki-the-open-window:1.23"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.24"
      ],
      "target": [
        "saki-the-open-window:1.24"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.25"
      ],
      "target": [
        "saki-the-open-window:1.25"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.26"
      ],
      "target": [
        "saki-the-open-window:1.26"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.27"
      ],
      "target": [
        "saki-the-open-window:1.27"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.28"
      ],
      "target": [
        "saki-the-open-window:1.28"
      ]
    },
    {
      "source": [
        "saki-the-open-window:1.29"
      ],
      "target": [
        "saki-the-open-window:1.29"
      ]
    }
  ]
}

=== streamentry/LitMundi/corpus/alignments/machado-um-apologo/machado-apologo-vi-ai-draft-2026.json
{
  "schema_version": 1,
  "work_id": "machado-um-apologo",
  "edition_id": "machado-apologo-vi-ai-draft-2026",
  "source_edition_id": "machado-apologo-pt-laemmert-1896",
  "links": [
    {
      "source": [
        "machado-um-apologo:1.1"
      ],
      "target": [
        "machado-um-apologo:1.1"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.2"
      ],
      "target": [
        "machado-um-apologo:1.2"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.3"
      ],
      "target": [
        "machado-um-apologo:1.3"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.4"
      ],
      "target": [
        "machado-um-apologo:1.4"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.5"
      ],
      "target": [
        "machado-um-apologo:1.5"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.6"
      ],
      "target": [
        "machado-um-apologo:1.6"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.7"
      ],
      "target": [
        "machado-um-apologo:1.7"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.8"
      ],
      "target": [
        "machado-um-apologo:1.8"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.9"
      ],
      "target": [
        "machado-um-apologo:1.9"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.10"
      ],
      "target": [
        "machado-um-apologo:1.10"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.11"
      ],
      "target": [
        "machado-um-apologo:1.11"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.12"
      ],
      "target": [
        "machado-um-apologo:1.12"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.13"
      ],
      "target": [
        "machado-um-apologo:1.13"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.14"
      ],
      "target": [
        "machado-um-apologo:1.14"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.15"
      ],
      "target": [
        "machado-um-apologo:1.15"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.16"
      ],
      "target": [
        "machado-um-apologo:1.16"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.17"
      ],
      "target": [
        "machado-um-apologo:1.17"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.18"
      ],
      "target": [
        "machado-um-apologo:1.18"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.19"
      ],
      "target": [
        "machado-um-apologo:1.19"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.20"
      ],
      "target": [
        "machado-um-apologo:1.20"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.21"
      ],
      "target": [
        "machado-um-apologo:1.21"
      ]
    },
    {
      "source": [
        "machado-um-apologo:1.22"
      ],
      "target": [
        "machado-um-apologo:1.22"
      ]
    }
  ]
}

=== streamentry/LitMundi/corpus/alignments/pardo-bazan-el-encaje-roto/pardo-encaje-vi-ai-draft-2026.json
{
  "schema_version": 1,
  "work_id": "pardo-bazan-el-encaje-roto",
  "edition_id": "pardo-encaje-vi-ai-draft-2026",
  "source_edition_id": "pardo-encaje-es-administracion-c1898",
  "links": [
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.1"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.1"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.2"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.2"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.3"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.3"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.4"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.4"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.5"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.5"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.6"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.6"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.7"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.7"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.8"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.8"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.9"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.9"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.10"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.10"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.11"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.11"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.12"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.12"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.13"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.13"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.14"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.14"
      ]
    },
    {
      "source": [
        "pardo-bazan-el-encaje-roto:1.15"
      ],
      "target": [
        "pardo-bazan-el-encaje-roto:1.15"
      ]
    }
  ]
}

=== streamentry/LitMundi/corpus/alignments/chopin-story-of-an-hour/chopin-hour-vi-ai-2026.json
{
  "schema_version": 1,
  "work_id": "chopin-story-of-an-hour",
  "edition_id": "chopin-hour-vi-ai-2026",
  "source_edition_id": "chopin-hour-en-1895",
  "links": [
    {
      "source": [
        "chopin-story-of-an-hour:1.1"
      ],
      "target": [
        "chopin-story-of-an-hour:1.1"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.2"
      ],
      "target": [
        "chopin-story-of-an-hour:1.2"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.3"
      ],
      "target": [
        "chopin-story-of-an-hour:1.3"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.4"
      ],
      "target": [
        "chopin-story-of-an-hour:1.4"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.5"
      ],
      "target": [
        "chopin-story-of-an-hour:1.5"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.6"
      ],
      "target": [
        "chopin-story-of-an-hour:1.6"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.7"
      ],
      "target": [
        "chopin-story-of-an-hour:1.7"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.8"
      ],
      "target": [
        "chopin-story-of-an-hour:1.8"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.9"
      ],
      "target": [
        "chopin-story-of-an-hour:1.9"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.10"
      ],
      "target": [
        "chopin-story-of-an-hour:1.10"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.11"
      ],
      "target": [
        "chopin-story-of-an-hour:1.11"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.12"
      ],
      "target": [
        "chopin-story-of-an-hour:1.12"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.13"
      ],
      "target": [
        "chopin-story-of-an-hour:1.13"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.14"
      ],
      "target": [
        "chopin-story-of-an-hour:1.14"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.15"
      ],
      "target": [
        "chopin-story-of-an-hour:1.15"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.16"
      ],
      "target": [
        "chopin-story-of-an-hour:1.16"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.17"
      ],
      "target": [
        "chopin-story-of-an-hour:1.17"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.18"
      ],
      "target": [
        "chopin-story-of-an-hour:1.18"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.19"
      ],
      "target": [
        "chopin-story-of-an-hour:1.19"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.20"
      ],
      "target": [
        "chopin-story-of-an-hour:1.20"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.21"
      ],
      "target": [
        "chopin-story-of-an-hour:1.21"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.22"
      ],
      "target": [
        "chopin-story-of-an-hour:1.22"
      ]
    },
    {
      "source": [
        "chopin-story-of-an-hour:1.23"
      ],
      "target": [
        "chopin-story-of-an-hour:1.23"
      ]
    }
  ]
}

=== streamentry/LitMundi/corpus/alignments/wilde-the-artist/wilde-artist-vi-ai-draft-2026.json
{
  "schema_version": 1,
  "work_id": "wilde-the-artist",
  "edition_id": "wilde-artist-vi-ai-draft-2026",
  "source_edition_id": "wilde-artist-en-methuen-1913",
  "links": [
    {
      "source": [
        "wilde-the-artist:1.1"
      ],
      "target": [
        "wilde-the-artist:1.1"
      ]
    },
    {
      "source": [
        "wilde-the-artist:1.2"
      ],
      "target": [
        "wilde-the-artist:1.2"
      ]
    },
    {
      "source": [
        "wilde-the-artist:1.3"
      ],
      "target": [
        "wilde-the-artist:1.3"
      ]
    },
    {
      "source": [
        "wilde-the-artist:1.4"
      ],
      "target": [
        "wilde-the-artist:1.4"
      ]
    },
    {
      "source": [
        "wilde-the-artist:1.5"
      ],
      "target": [
        "wilde-the-artist:1.5"
      ]
    }
  ]
}
